version: '3'

services:
  web:
    build: .
    container_name: foodle-app-server
    env_file: .env
    command: yarn run dev
    ports:
      - "5000:8888"
  db:
    image: postgres:10.15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_ID:${POSTGRES_ID}
      POSTGRES_KEY:${POSTGRES_KEY}
